# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  test:
    cmds:
      - uv run pytest
    desc: Run the test suite

  lint:
    cmds:
      - uv run ruff check .

  check-format:
    cmds:
      - uv run ruff format --check

  apply-format:
    cmds:
      - uv run ruff format .
  
  build:
    cmds:
      - uv build

  clean:
    desc: Remove build artifacts and Python caches
    cmds:
      - rm -rf build/ dist/ *.egg-info
      - find . -type d -name "__pycache__" -exec rm -rf {} + || true
      - find . -name "*.pyc" -delete || true

  check-before-push:
    desc: Run checks before
    deps:
      - test
      - lint
      - check-format
